# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('save_the_date_sent', models.BooleanField(default=False)),
                ('save_the_date_opened', models.BooleanField(default=False)),
                ('invited', models.BooleanField(default=False)),
                ('attending', models.NullBooleanField(default=None)),
            ],
        ),
    ]
