# Generated by Django 3.2.9 on 2021-12-11 03:08

from django.db import migrations, models
import django.db.models.deletion
import guests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('family', models.CharField(choices=[('kim', 'Kim'), ('jake', 'Jake')], default='', max_length=10)),
                ('type', models.CharField(choices=[('formal', 'formal'), ('fun', 'fun')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('save_the_date_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('save_the_date_opened', models.DateTimeField(blank=True, default=None, null=True)),
                ('invitation_id', models.CharField(db_index=True, default=guests.models._random_uuid, max_length=32, unique=True)),
                ('invitation_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('invitation_opened', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_invited', models.BooleanField(default=False)),
                ('is_attending', models.NullBooleanField(default=None)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('is_attending', models.NullBooleanField(default=None)),
                ('tea_ceremony', models.BooleanField(default=False)),
                ('meal', models.CharField(blank=True, choices=[('beef', 'cow'), ('fish', 'fish'), ('hen', 'hen'), ('vegetarian', 'vegetable')], max_length=20, null=True)),
                ('is_child', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.party')),
            ],
        ),
    ]
