# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20160116_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
