# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20160123_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='save_the_date_opened',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='save_the_date_sent',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
