# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20160207_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
