# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 12:32
from __future__ import unicode_literals
import uuid

from django.db import migrations


def reset_invitation_ids(apps, schema_editor):
    Party = apps.get_model("guests", "Party")
    for party in Party.objects.all():
        party.invitation_id = uuid.uuid4().hex
        party.save()


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_auto_20160320_1342'),
    ]

    operations = [
        migrations.RunPython(reset_invitation_ids),
    ]
