# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0013_auto_20160326_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('beef', 'cow'), ('fish', 'fish'), ('hen', 'hen'), ('vegetarian', 'vegetable')], max_length=20, null=True),
        ),
    ]
