# Generated by Django 2.0.4 on 2018-04-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20180219_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='category',
        ),
        migrations.RemoveField(
            model_name='party',
            name='rehearsal_dinner',
        ),
        migrations.RemoveField(
            model_name='party',
            name='type',
        ),
        migrations.AddField(
            model_name='party',
            name='lang',
            field=models.CharField(blank=True, choices=[('en', 'en'), ('es', 'es'), ('fr', 'fr')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('meat', 'meat option'), ('vegetarian', 'vegetarian option')], max_length=20, null=True),
        ),
    ]
