# Generated by Django 3.0.2 on 2020-01-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_guest_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='meal',
        ),
    ]
