# Generated by Django 3.2.9 on 2021-11-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20211104_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='side',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='side',
            new_name='family',
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('formal', 'formal'), ('fun', 'fun')], max_length=10),
        ),
    ]
