# Generated by Django 3.2.9 on 2021-11-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_auto_20211104_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='category',
        ),
        migrations.RemoveField(
            model_name='party',
            name='rehearsal_dinner',
        ),
        migrations.AddField(
            model_name='guest',
            name='tea_ceremony',
            field=models.BooleanField(default=False),
        ),
    ]
